### PR TITLE
Developed basic search feature (can only search records, displays 50, have to press the search button each time you want to search)

### PR DESCRIPTION
**Pull request by mrzengel**

### CODE REVIEW

**Comment by garciagenrique** [comment]
Looks very nice @mrzengel !!

Few little comments.
When launching the extension (by using the command `jupyter lab`), I found the following error, besides everything seems to work very well.

```
zenodo_jupyterlab | extension failed loading with message: ExtensionLoadingError('_load_jupyter_server_extension function was not found.')
    Traceback (most recent call last):
      File "/root/miniconda3/envs/dev_zen/lib/python3.11/site-packages/jupyter_server/extension/manager.py", line 360, in load_extension
        extension.load_all_points(self.serverapp)
      File "/root/miniconda3/envs/dev_zen/lib/python3.11/site-packages/jupyter_server/extension/manager.py", line 232, in load_all_points
        return [self.load_point(point_name, serverapp) for point_name in self.extension_points]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/miniconda3/envs/dev_zen/lib/python3.11/site-packages/jupyter_server/extension/manager.py", line 232, in <listcomp>
        return [self.load_point(point_name, serverapp) for point_name in self.extension_points]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/miniconda3/envs/dev_zen/lib/python3.11/site-packages/jupyter_server/extension/manager.py", line 223, in load_point
        return point.load(serverapp)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/root/miniconda3/envs/dev_zen/lib/python3.11/site-packages/jupyter_server/extension/manager.py", line 150, in load
        loader = self._get_loader()
                 ^^^^^^^^^^^^^^^^^^
      File "/root/miniconda3/envs/dev_zen/lib/python3.11/site-packages/jupyter_server/extension/manager.py", line 119, in _get_loader
        loader = get_loader(loc)
                 ^^^^^^^^^^^^^^^
      File "/root/miniconda3/envs/dev_zen/lib/python3.11/site-packages/jupyter_server/extension/utils.py", line 40, in get_loader
        raise ExtensionLoadingError(msg) from None
    jupyter_server.extension.utils.ExtensionLoadingError: _load_jupyter_server_extension function was not found.
[I 2024-07-15 17:56:30.372 ServerApp] Registered zenodo_jupyterlab server extension
[I 2024-07-15 17:56:30.372 ServerApp] zenodo_jupyterlab.server | extension was successfully loaded.
```

**Comment by mrzengel** [comment]
Hmmm, that seems to be a remnant from when I thought the server extension was named zenodo_jupyterlab and not zenodo_jupyterlab.server. The actual server extension at zenodo_jupyterlab.server seems to be working fine based on the error, and it should just be some housekeeping to clean up that old call somewhere. I don't get that error anymore, though. I'll look into it tomorrow, but it shouldn't affect functionality.

**Comment by garciagenrique** [comment]
Also, I have mentioned not to focus a lot in the "aesthetics", but I think that an horizontal scrolling bar would very much improve the user experience. Could you have a look if this could be implemented as easy as possible ?

A basic search looks like this for me in a mid-size screen (plus it would avoid making that the extension takes half of the screen)
Screenshot 2024-07-15 at 18 03 35

**Comment by garciagenrique** [comment]
> Hmmm, that seems to be a remnant from when I thought the server extension was named zenodo_jupyterlab and not zenodo_jupyterlab.server. The actual server extension at zenodo_jupyterlab.server seems to be working fine based on the error, and it should just be some housekeeping to clean up that old call somewhere. I don't get that error anymore, though. I'll look into it tomorrow, but it shouldn't affect functionality.

Ah, I see. I run `jupyter server extension enable zenodo_jupyterlab` instead of `jupyter server extension enable zenodo_jupyterlab.server`. Any idea of the difference ?

**Comment by mrzengel** [comment]
The only difference is one of preference. I put the server extension code within `zenodo_jupyterlab/server` rather than mixing it with the jupyterlab extension code in the parent directory. It should have no effect on performance and just makes organization a bit cleaner in my mind.

**Review by garciagenrique — APPROVED** [review]

**Pull request merged**
